### ISSUE TITLE
Convert 2016 general election precinct results to CSV

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-hi#1]
Using the [text file produced by the state](http://files.hawaii.gov/elections/files/results/2016/general/media.txt), generate a CSV file with the following headers:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

For the following offices: President, U.S. Senate, U.S. House, State Senate, State House. You can include the other offices but you don't have to.

The filename should be `20161108__hi__general__precinct.csv` and it goes in a `2016` folder.

**Comment by dphID** [comment]
1. Is there a data file that provides CountyNames for Precincts?
2. Does "01-02" (first column) translate to: Precinct=01 ; District=02?
3. Should Candidate specify only one name e.g., Trump, Donald (dropping Pence)?
4. Should Party include (or not) the parentheses?
5. For Office, do you want 'Representative' translated to 'House'

**Comment by dphID** [comment]
Have answers for (1) and (2)

**Comment by dphID** [comment]
Sample Data (subject to change re: Qs 3,4,5):

"county","precinct","office","district","party","candidate","votes"
"County of Hawaii","01","President and Vice President","01","G","STEIN, Jill","49"
"County of Hawaii","01","President and Vice President","01","L","JOHNSON, Gary","35"
"County of Hawaii","01","President and Vice President","01","R","TRUMP, Donald J.","179"
"County of Hawaii","01","President and Vice President","01","D","CLINTON, Hillary","470"
"County of Hawaii","01","President and Vice President","01","C","CASTLE, Darrell L.","5"
"County of Hawaii","01","U.S. Senator","01","A","GIUFFRE, John M. (Raghu)","4"
"County of Hawaii","01","U.S. Senator","01","C","ALLISON, Joy J.","22"
"County of Hawaii","01","U.S. Senator","01","D","SCHATZ, Brian","518"
"County of Hawaii","01","U.S. Senator","01","L","KOKOSKI, Michael A.","17"
"County of Hawaii","01","U.S. Senator","01","R","CARROLL, John","152"

**Comment by dwillis** [comment]
That looks good, thanks! No parens for parties if possible, you can drop secondary names from candidates and yes, please turn "Representative" into "House".

**Comment by dphID** [comment]
This is my first time on GitHub, can you explain how I upload the output file -- thanks.

**Comment by dwillis** [comment]
Sure! Since it's your first time, it might be easier for you to send it to openelections@gmail.com, but if you're familiar with Git, you can fork this repository to your own Github account, add the file to that repository locally (either via the command line or by uploading it) and then create a pull request. Whatever is easiest for you!
